### PR TITLE
proj00 pull request

### PR DESCRIPTION
**Pull request by andyyy60**

### CODE REVIEW

**Comment by rhelmot** [comment]
Hey guys, you made a pretty serious error that I should have helped you with during lab but I didn't see this until now. You made this pull request from the master branch, and then continued to push to the master branch while working on project 1.

If you'd like help with this, come to open lab hours or ask me for help during lab.

If you'd like to do it on your own, here are the steps:

make sure your have a project 1 branch, and that there's no uncommitted work
git checkout master (switch to the master branch. make sure this works so the next step doesn't mess up your other branches)
git reset --hard b4bd1d2 (that's the last commit that you want to include in this pull request)
git push -f origin master (force-push your changes)

**Comment by andyyy60** [comment]
Hi Audrey,

Thanks for the heads up! I am trying to fix this but it seems like
commit b4bd1d2
does not exist. I get the following error:

fatal: ambiguous argument 'b4bd1d2': unknown revision or path not in the
working tree.
I did the checkout the master branch, and even went on the web browser and
could not find any commit containing that string.

Thanks,
Andy.

**Comment by rhelmot** [comment]
..shit I copied those instructions from another group who made the same mistake and forgot to change the hash. the commit you want is e25a0eb, since this is the last commit for project 0.

**Comment by andyyy60** [comment]
Okay! I performed those instructions -- I can see my changes in both
branches. Is it okay now?

**Comment by rhelmot** [comment]
no... it is not. If you click the "files changed" tab at the top of this pull request you can see that despite it being the proj00 pull request it contains the changes for project 1 as well.

**Comment by andyyy60** [comment]
I see, I misread the email and thought the problem was that our master
branch wasn't updated with proj01 branch.

If I understand correctly, the pull request #9 should only contain stuff
from the proj00. I have reverted the changes but it seems that if I want to
create a new pull request for proj01 it automatically changes my master
branch to the contents of proj01, and in turn changes the content of the
proj00 pull request (#9)

How can I create a new pull request for proj01 that will not interfere with
this pull request (#9)?

**Comment by rhelmot** [comment]
Pull requests on github are linked to branches. You need a distinct branch for each pull request. You have a branch for proj01 and then submit a new pull request from your proj01 to our master.

**Pull request merged**
